### ISSUE TITLE
Small syntax error when giving it ./path_to_file.tar

### ISSUE THREAD

**Issue by jamestwebber** [chanzuckerberg/s3mi#4]
Trying this out to download some big files onto an EC2 instance. I ran into an error when I tried `s3cp.py s3://path-to-data/big_file.tar ./big_file.tar` but it seems to be downloading just fine with `s3cp.py s3://path-to-data/big_file.tar big_file.tar`. I'm guessing you just made an insufficiently general assumption about the argument paths.

Once I got it to work downloading appears to be crazy fast, though 👍

**Comment by boris-dimitrov** [comment]
Yep, sorry.   Will fix soon.

**Comment by boris-dimitrov** [comment]
Fixed in version 0.3.0.
